# Generated by Django 6.0.1 on 2026-01-12 06:28

import django.core.validators
import django.db.models.deletion
import django.utils.timezone
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('attendance', '0002_auditlog_alter_attendancerecord_options_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AcademicLevel',
            fields=[
                ('code', models.CharField(max_length=10, primary_key=True, serialize=False, unique=True)),
                ('name', models.CharField(max_length=50)),
                ('level_type', models.CharField(choices=[('SMP', 'Sekolah Menengah Pertama'), ('SMA', 'Sekolah Menengah Atas'), ('MA', 'Madrasah Aliyah'), ('MTS', 'Madrasah Tsanawiyah')], max_length=10)),
                ('description', models.TextField(blank=True)),
                ('is_active', models.BooleanField(default=True)),
                ('min_grade', models.PositiveIntegerField(help_text='Minimum grade level (e.g., 7 for SMP)')),
                ('max_grade', models.PositiveIntegerField(help_text='Maximum grade level (e.g., 9 for SMP)')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Academic Level',
                'verbose_name_plural': 'Academic Levels',
                'ordering': ['level_type', 'code'],
            },
        ),
        migrations.CreateModel(
            name='Classroom',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('grade', models.PositiveIntegerField(help_text='Grade level (7, 8, 9, 10, 11, 12)')),
                ('section', models.CharField(blank=True, help_text='Class section (A, B, C, etc.)', max_length=5)),
                ('name', models.CharField(help_text='Display name for the classroom', max_length=50)),
                ('capacity', models.PositiveIntegerField(default=30)),
                ('room_number', models.CharField(blank=True, max_length=20)),
                ('is_active', models.BooleanField(default=True)),
                ('academic_year', models.CharField(help_text='Academic year (e.g., 2024/2025)', max_length=9)),
            ],
            options={
                'verbose_name': 'Classroom',
                'verbose_name_plural': 'Classrooms',
                'ordering': ['academic_level', 'grade', 'section'],
            },
        ),
        migrations.AlterModelOptions(
            name='attendancerecord',
            options={'ordering': ['-date', 'student__name'], 'verbose_name': 'Attendance Record', 'verbose_name_plural': 'Attendance Records'},
        ),
        migrations.AlterModelOptions(
            name='attendancesummary',
            options={'ordering': ['-year', '-month', 'student__name'], 'verbose_name': 'Attendance Summary', 'verbose_name_plural': 'Attendance Summaries'},
        ),
        migrations.AlterModelOptions(
            name='student',
            options={'ordering': ['name'], 'verbose_name': 'Student', 'verbose_name_plural': 'Students'},
        ),
        migrations.RemoveIndex(
            model_name='student',
            name='attendance__class_n_54b5f1_idx',
        ),
        migrations.AddField(
            model_name='student',
            name='enrollment_date',
            field=models.DateField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='student',
            name='graduation_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='student',
            name='student_number',
            field=models.CharField(blank=True, help_text='Internal student number', max_length=20),
        ),
        migrations.AlterField(
            model_name='student',
            name='gender',
            field=models.CharField(blank=True, choices=[('M', 'Laki-laki'), ('F', 'Perempuan')], max_length=1),
        ),
        migrations.AlterField(
            model_name='student',
            name='student_id',
            field=models.CharField(help_text='Unique student identifier', max_length=10, unique=True, validators=[django.core.validators.RegexValidator(message='Student ID must be 2-10 characters long and contain only numbers and uppercase letters', regex='^[0-9A-Z]{2,10}$')]),
        ),
        migrations.AddField(
            model_name='classroom',
            name='academic_level',
            field=models.ForeignKey(help_text='Academic level (SMP/SMA)', on_delete=django.db.models.deletion.CASCADE, to='attendance.academiclevel'),
        ),
        migrations.AddField(
            model_name='classroom',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_created', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='classroom',
            name='homeroom_teacher',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='homeroom_classes', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='classroom',
            name='updated_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_updated', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='student',
            name='classroom',
            field=models.ForeignKey(blank=True, help_text="Student's classroom", null=True, on_delete=django.db.models.deletion.CASCADE, related_name='students', to='attendance.classroom'),
        ),
        migrations.AddIndex(
            model_name='student',
            index=models.Index(fields=['classroom'], name='attendance__classro_c3505d_idx'),
        ),
        migrations.AddIndex(
            model_name='student',
            index=models.Index(fields=['enrollment_date'], name='attendance__enrollm_44dda3_idx'),
        ),
        migrations.RemoveField(
            model_name='student',
            name='class_name',
        ),
        migrations.AddIndex(
            model_name='classroom',
            index=models.Index(fields=['academic_level', 'grade'], name='attendance__academi_3ac2f4_idx'),
        ),
        migrations.AddIndex(
            model_name='classroom',
            index=models.Index(fields=['is_active'], name='attendance__is_acti_c622af_idx'),
        ),
        migrations.AddIndex(
            model_name='classroom',
            index=models.Index(fields=['academic_year'], name='attendance__academi_b0a749_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='classroom',
            unique_together={('academic_level', 'grade', 'section', 'academic_year')},
        ),
    ]
