# Generated by Django 6.0.1 on 2026-01-12 06:40

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('attendance', '0003_academiclevel_classroom_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='classroom',
            field=models.ForeignKey(help_text="Student's classroom", on_delete=django.db.models.deletion.CASCADE, related_name='students', to='attendance.classroom'),
        ),
    ]
