# Generated by Django 6.0.1 on 2026-01-12 09:37

import django.core.validators
import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('attendance', '0004_alter_student_classroom'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='DaySchedule',
            fields=[
                ('day_of_week', models.IntegerField(choices=[(0, 'Senin'), (1, 'Selasa'), (2, 'Rabu'), (3, 'Kamis'), (4, 'Jumat'), (5, 'Sabtu'), (6, 'Minggu')], help_text='Day of week (0=Senin, 6=Minggu)', primary_key=True, serialize=False, unique=True)),
                ('day_name', models.CharField(help_text='Display name for the day', max_length=10)),
                ('default_jp_count', models.PositiveIntegerField(help_text='Number of JP (Jam Pelajaran) for this day (1-10)', validators=[django.core.validators.MinValueValidator(1, message='JP count must be at least 1'), django.core.validators.MaxValueValidator(10, message='JP count cannot exceed 10')])),
                ('is_school_day', models.BooleanField(default=True, help_text='Whether this is a school day')),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='dayschedule_updated', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Day Schedule',
                'verbose_name_plural': 'Day Schedules',
                'ordering': ['day_of_week'],
            },
        ),
        migrations.CreateModel(
            name='DailyAttendance',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('date', models.DateField(help_text='Date of attendance')),
                ('jp_statuses', models.JSONField(default=dict, help_text='JP statuses as JSON: {"1": "H", "2": "H", "3": "S", ...}')),
                ('notes', models.TextField(blank=True, help_text='Additional notes about the attendance')),
                ('recorded_at', models.DateTimeField(auto_now_add=True, help_text='Timestamp when attendance was recorded')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_created', to=settings.AUTH_USER_MODEL)),
                ('recorded_by', models.ForeignKey(help_text='User who recorded this attendance', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='recorded_attendances', to=settings.AUTH_USER_MODEL)),
                ('student', models.ForeignKey(help_text='Student for this attendance record', on_delete=django.db.models.deletion.CASCADE, related_name='daily_attendances', to='attendance.student')),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_updated', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Daily Attendance',
                'verbose_name_plural': 'Daily Attendances',
                'ordering': ['-date', 'student__name'],
                'indexes': [models.Index(fields=['date'], name='attendance__date_370344_idx'), models.Index(fields=['student', 'date'], name='attendance__student_ed8b4b_idx')],
                'unique_together': {('student', 'date')},
            },
        ),
        migrations.CreateModel(
            name='Holiday',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('date', models.DateField(help_text='Date of the holiday')),
                ('name', models.CharField(help_text='Name of the holiday', max_length=100)),
                ('holiday_type', models.CharField(choices=[('UAS', 'Ujian Akhir Semester'), ('UN', 'Ujian Nasional'), ('PESANTREN', 'Libur Pesantren'), ('LAINNYA', 'Lainnya')], help_text='Type of holiday', max_length=20)),
                ('apply_to_all', models.BooleanField(default=True, help_text='If True, applies to all classrooms')),
                ('description', models.TextField(blank=True, help_text='Additional description about the holiday')),
                ('classrooms', models.ManyToManyField(blank=True, help_text='Specific classrooms this holiday applies to (if apply_to_all is False)', related_name='holidays', to='attendance.classroom')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_created', to=settings.AUTH_USER_MODEL)),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_updated', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Holiday',
                'verbose_name_plural': 'Holidays',
                'ordering': ['-date'],
                'indexes': [models.Index(fields=['date'], name='attendance__date_54d65e_idx'), models.Index(fields=['apply_to_all'], name='attendance__apply_t_4180a8_idx')],
            },
        ),
    ]
