# Generated by Django 6.0.1 on 2026-01-12 09:38

from django.db import migrations


def populate_day_schedule(apps, schema_editor):
    """Populate DaySchedule with default JP counts for each day of the week"""
    DaySchedule = apps.get_model('attendance', 'DaySchedule')
    
    # Default JP counts per day:
    # Senin-Kamis: 6 JP, Jumat: 4 JP, Sabtu: 6 JP, Minggu: 0 JP (not school day)
    day_schedules = [
        {'day_of_week': 0, 'day_name': 'Senin', 'default_jp_count': 6, 'is_school_day': True},
        {'day_of_week': 1, 'day_name': 'Selasa', 'default_jp_count': 6, 'is_school_day': True},
        {'day_of_week': 2, 'day_name': 'Rabu', 'default_jp_count': 6, 'is_school_day': True},
        {'day_of_week': 3, 'day_name': 'Kamis', 'default_jp_count': 6, 'is_school_day': True},
        {'day_of_week': 4, 'day_name': 'Jumat', 'default_jp_count': 4, 'is_school_day': True},
        {'day_of_week': 5, 'day_name': 'Sabtu', 'default_jp_count': 6, 'is_school_day': True},
        {'day_of_week': 6, 'day_name': 'Minggu', 'default_jp_count': 0, 'is_school_day': False},
    ]
    
    for schedule_data in day_schedules:
        DaySchedule.objects.create(**schedule_data)


def reverse_populate_day_schedule(apps, schema_editor):
    """Remove all DaySchedule records"""
    DaySchedule = apps.get_model('attendance', 'DaySchedule')
    DaySchedule.objects.all().delete()


class Migration(migrations.Migration):

    dependencies = [
        ('attendance', '0005_add_jp_attendance_models'),
    ]

    operations = [
        migrations.RunPython(populate_day_schedule, reverse_populate_day_schedule),
    ]
