# Generated by Django 6.0.1 on 2026-01-15 09:58

import django.core.validators
import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('attendance', '0009_populate_remaining_students'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Teacher',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('teacher_id', models.CharField(help_text='Unique teacher identifier', max_length=10, unique=True, validators=[django.core.validators.RegexValidator(message='Teacher ID must be 2-10 characters long and contain only numbers and uppercase letters', regex='^[0-9A-Z]{2,10}$')])),
                ('nip', models.CharField(blank=True, help_text='Nomor Induk Pegawai (18 digits)', max_length=18, validators=[django.core.validators.RegexValidator(message='NIP must be exactly 18 digits', regex='^\\d{18}$')])),
                ('name', models.CharField(help_text='Full name of the teacher', max_length=100, validators=[django.core.validators.MinLengthValidator(2)])),
                ('subjects', models.TextField(blank=True, help_text='Mata pelajaran yang diajar (comma-separated)')),
                ('is_active', models.BooleanField(default=True)),
                ('academic_year', models.CharField(help_text='Academic year (e.g., 2024/2025)', max_length=9)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_created', to=settings.AUTH_USER_MODEL)),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_updated', to=settings.AUTH_USER_MODEL)),
                ('user', models.OneToOneField(blank=True, help_text='User account for login (if applicable)', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='teacher_profile', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Teacher',
                'verbose_name_plural': 'Teachers',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='TeacherDailyAttendance',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('date', models.DateField(help_text='Date of attendance')),
                ('jp_statuses', models.JSONField(default=dict, help_text='JP statuses as JSON: {"1": "H", "2": "H", "3": "S", ...}')),
                ('notes', models.TextField(blank=True, help_text='Additional notes (e.g., replacement info)')),
                ('is_replacement', models.BooleanField(default=False, help_text='Flag if this includes replacement teaching')),
                ('recorded_at', models.DateTimeField(auto_now_add=True, help_text='Timestamp when attendance was recorded')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_created', to=settings.AUTH_USER_MODEL)),
                ('recorded_by', models.ForeignKey(help_text='User who recorded this attendance', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='teacher_recorded_attendances', to=settings.AUTH_USER_MODEL)),
                ('replaced_teacher', models.ForeignKey(blank=True, help_text='Teacher being replaced (if applicable)', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='replacements_received', to='attendance.teacher')),
                ('teacher', models.ForeignKey(help_text='Teacher for this attendance record', on_delete=django.db.models.deletion.CASCADE, related_name='teacher_daily_attendances', to='attendance.teacher')),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_updated', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Teacher Daily Attendance',
                'verbose_name_plural': 'Teacher Daily Attendances',
                'ordering': ['-date', 'teacher__name'],
            },
        ),
        migrations.CreateModel(
            name='TeacherSchedule',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('day_of_week', models.IntegerField(choices=[(0, 'Senin'), (1, 'Selasa'), (2, 'Rabu'), (3, 'Kamis'), (4, 'Jumat'), (5, 'Sabtu'), (6, 'Minggu')], help_text='Day of week (0=Senin, 6=Minggu)')),
                ('jp_numbers', models.JSONField(default=list, help_text='JP numbers as JSON array: [1, 2, 3, ...]')),
                ('subject', models.CharField(blank=True, help_text='Mata pelajaran yang diajar', max_length=100)),
                ('is_piket', models.BooleanField(default=False, help_text='Apakah hari piket')),
                ('academic_year', models.CharField(help_text='Academic year (e.g., 2024/2025)', max_length=9)),
                ('notes', models.TextField(blank=True, help_text='Additional notes')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_created', to=settings.AUTH_USER_MODEL)),
                ('teacher', models.ForeignKey(help_text='Teacher for this schedule', on_delete=django.db.models.deletion.CASCADE, related_name='schedules', to='attendance.teacher')),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_updated', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Teacher Schedule',
                'verbose_name_plural': 'Teacher Schedules',
                'ordering': ['teacher', 'day_of_week'],
            },
        ),
        migrations.AddIndex(
            model_name='teacher',
            index=models.Index(fields=['teacher_id'], name='attendance__teacher_033ae2_idx'),
        ),
        migrations.AddIndex(
            model_name='teacher',
            index=models.Index(fields=['nip'], name='attendance__nip_e5c0c3_idx'),
        ),
        migrations.AddIndex(
            model_name='teacher',
            index=models.Index(fields=['is_active'], name='attendance__is_acti_fabcdd_idx'),
        ),
        migrations.AddIndex(
            model_name='teacher',
            index=models.Index(fields=['user'], name='attendance__user_id_5d4409_idx'),
        ),
        migrations.AddIndex(
            model_name='teacherdailyattendance',
            index=models.Index(fields=['date'], name='attendance__date_806db9_idx'),
        ),
        migrations.AddIndex(
            model_name='teacherdailyattendance',
            index=models.Index(fields=['teacher', 'date'], name='attendance__teacher_e43212_idx'),
        ),
        migrations.AddIndex(
            model_name='teacherdailyattendance',
            index=models.Index(fields=['is_replacement'], name='attendance__is_repl_2e89fa_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='teacherdailyattendance',
            unique_together={('teacher', 'date')},
        ),
        migrations.AddIndex(
            model_name='teacherschedule',
            index=models.Index(fields=['teacher', 'day_of_week'], name='attendance__teacher_a2057a_idx'),
        ),
        migrations.AddIndex(
            model_name='teacherschedule',
            index=models.Index(fields=['academic_year'], name='attendance__academi_87ab72_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='teacherschedule',
            unique_together={('teacher', 'day_of_week', 'academic_year')},
        ),
    ]
