# Generated by Django 6.0.1 on 2026-01-21 07:02

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('attendance', '0009_populate_remaining_students'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Subject',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('code', models.CharField(help_text='Unique subject code (uppercase alphanumeric)', max_length=10, unique=True)),
                ('name', models.CharField(help_text='Subject name', max_length=100)),
                ('category', models.CharField(choices=[('AGAMA', 'Pendidikan Agama'), ('UMUM', 'Pendidikan Umum'), ('KETERAMPILAN', 'Keterampilan'), ('EKSTRAKURIKULER', 'Ekstrakurikuler')], help_text='Subject category', max_length=20)),
                ('description', models.TextField(blank=True, help_text='Subject description')),
                ('is_active', models.BooleanField(default=True, help_text='Whether this subject is currently active')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_created', to=settings.AUTH_USER_MODEL)),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_updated', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Subject',
                'verbose_name_plural': 'Subjects',
                'ordering': ['category', 'name'],
                'indexes': [models.Index(fields=['code'], name='attendance__code_a66249_idx'), models.Index(fields=['category'], name='attendance__categor_6f750c_idx'), models.Index(fields=['is_active'], name='attendance__is_acti_5fc403_idx')],
            },
        ),
    ]
