# Generated by Django 6.0.1 on 2026-01-15 10:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('attendance', '0010_teacher_teacherdailyattendance_teacherschedule_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='teacherschedule',
            options={'ordering': ['teacher', 'day_of_week', 'jp_numbers'], 'verbose_name': 'Teacher Schedule', 'verbose_name_plural': 'Teacher Schedules'},
        ),
        migrations.AlterUniqueTogether(
            name='teacherschedule',
            unique_together=set(),
        ),
    ]
