# Generated by Django 6.0.1 on 2026-01-21 07:24

import django.core.validators
import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('attendance', '0010_subject'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Teacher',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('nip', models.CharField(help_text='Nomor Induk Pegawai (unique, max 20 characters)', max_length=20, unique=True, validators=[django.core.validators.RegexValidator(message='NIP must be 1-20 characters long and contain only numbers and uppercase letters', regex='^[0-9A-Z]{1,20}$')])),
                ('full_name', models.CharField(help_text='Full name of the teacher', max_length=100, validators=[django.core.validators.MinLengthValidator(3)])),
                ('photo', models.ImageField(blank=True, help_text='Teacher photo', null=True, upload_to='teachers/')),
                ('email', models.EmailField(blank=True, help_text='Email address', max_length=254)),
                ('phone', models.CharField(blank=True, help_text='Phone number', max_length=15)),
                ('address', models.TextField(blank=True, help_text='Home address')),
                ('employment_date', models.DateField(help_text='Date when teacher started employment')),
                ('employment_status', models.CharField(choices=[('ACTIVE', 'Aktif'), ('LEAVE', 'Cuti'), ('INACTIVE', 'Tidak Aktif')], default='ACTIVE', help_text='Current employment status', max_length=10)),
                ('is_homeroom_teacher', models.BooleanField(default=False, help_text='Whether this teacher is a homeroom teacher')),
                ('is_active', models.BooleanField(default=True, help_text='Whether this teacher is currently active')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_created', to=settings.AUTH_USER_MODEL)),
                ('homeroom_class', models.ForeignKey(blank=True, help_text='Homeroom class if applicable', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='homeroom_teachers', to='attendance.classroom')),
                ('subjects', models.ManyToManyField(blank=True, help_text='Subjects taught by this teacher', related_name='teachers', to='attendance.subject')),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_updated', to=settings.AUTH_USER_MODEL)),
                ('user', models.OneToOneField(blank=True, help_text='Associated user account for self-attendance', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='teacher_profile', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Teacher',
                'verbose_name_plural': 'Teachers',
                'ordering': ['full_name'],
                'indexes': [models.Index(fields=['nip'], name='attendance__nip_e5c0c3_idx'), models.Index(fields=['user'], name='attendance__user_id_5d4409_idx'), models.Index(fields=['is_active'], name='attendance__is_acti_fabcdd_idx'), models.Index(fields=['employment_status'], name='attendance__employm_c8c79c_idx')],
            },
        ),
    ]
