# Generated by Django 6.0.1 on 2026-01-21 07:30

import django.core.validators
import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('attendance', '0011_add_teacher_model'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='TeacherSchedule',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('day_of_week', models.IntegerField(choices=[(0, 'Senin'), (1, 'Selasa'), (2, 'Rabu'), (3, 'Kamis'), (4, 'Jumat'), (5, 'Sabtu'), (6, 'Minggu')], help_text='Day of week (0=Senin, 6=Minggu)')),
                ('jp_start', models.PositiveIntegerField(help_text='Starting JP (1-10)', validators=[django.core.validators.MinValueValidator(1, message='JP start must be at least 1'), django.core.validators.MaxValueValidator(10, message='JP start cannot exceed 10')])),
                ('jp_end', models.PositiveIntegerField(help_text='Ending JP (1-10)', validators=[django.core.validators.MinValueValidator(1, message='JP end must be at least 1'), django.core.validators.MaxValueValidator(10, message='JP end cannot exceed 10')])),
                ('room_number', models.CharField(blank=True, help_text='Room number where class is held', max_length=20)),
                ('notes', models.TextField(blank=True, help_text='Additional notes about the schedule')),
                ('effective_date', models.DateField(help_text='Date when this schedule becomes effective')),
                ('end_date', models.DateField(blank=True, help_text='Date when this schedule ends (optional)', null=True)),
                ('is_active', models.BooleanField(default=True, help_text='Whether this schedule is currently active')),
                ('classroom', models.ForeignKey(help_text='Classroom where teaching occurs', on_delete=django.db.models.deletion.CASCADE, related_name='teacher_schedules', to='attendance.classroom')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_created', to=settings.AUTH_USER_MODEL)),
                ('subject', models.ForeignKey(help_text='Subject being taught', on_delete=django.db.models.deletion.CASCADE, related_name='schedules', to='attendance.subject')),
                ('teacher', models.ForeignKey(help_text='Teacher assigned to this schedule', on_delete=django.db.models.deletion.CASCADE, related_name='schedules', to='attendance.teacher')),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_updated', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Teacher Schedule',
                'verbose_name_plural': 'Teacher Schedules',
                'ordering': ['day_of_week', 'jp_start', 'teacher__full_name'],
                'indexes': [models.Index(fields=['teacher', 'day_of_week', 'jp_start'], name='attendance__teacher_1d8aa4_idx'), models.Index(fields=['classroom', 'day_of_week', 'jp_start'], name='attendance__classro_eef28c_idx'), models.Index(fields=['is_active'], name='attendance__is_acti_dc6c58_idx'), models.Index(fields=['effective_date'], name='attendance__effecti_eb9e5a_idx')],
                'constraints': [models.UniqueConstraint(fields=('teacher', 'day_of_week', 'jp_start', 'jp_end', 'effective_date'), name='unique_teacher_schedule')],
            },
        ),
    ]
