# Generated by Django 6.0.1 on 2026-01-21 07:38

import django.core.validators
import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('attendance', '0012_add_teacher_schedule'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='TeacherAttendance',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('date', models.DateField(help_text='Date of attendance')),
                ('jp_number', models.PositiveIntegerField(help_text='JP number (1-10)', validators=[django.core.validators.MinValueValidator(1, message='JP number must be at least 1'), django.core.validators.MaxValueValidator(10, message='JP number cannot exceed 10')])),
                ('status', models.CharField(choices=[('HADIR', 'Hadir'), ('SAKIT', 'Sakit'), ('IZIN', 'Izin'), ('CUTI', 'Cuti'), ('DINAS', 'Dinas Luar'), ('ALPA', 'Alpa')], help_text='Attendance status', max_length=10)),
                ('notes', models.TextField(blank=True, help_text='Additional notes about the attendance')),
                ('is_substitute', models.BooleanField(default=False, help_text='Whether this is substitute teaching')),
                ('recorded_at', models.DateTimeField(auto_now_add=True, help_text='Timestamp when attendance was recorded')),
                ('latitude', models.DecimalField(blank=True, decimal_places=6, help_text='Latitude coordinate for location validation', max_digits=9, null=True, validators=[django.core.validators.MinValueValidator(-90, message='Latitude must be between -90 and 90'), django.core.validators.MaxValueValidator(90, message='Latitude must be between -90 and 90')])),
                ('longitude', models.DecimalField(blank=True, decimal_places=6, help_text='Longitude coordinate for location validation', max_digits=9, null=True, validators=[django.core.validators.MinValueValidator(-180, message='Longitude must be between -180 and 180'), django.core.validators.MaxValueValidator(180, message='Longitude must be between -180 and 180')])),
                ('is_location_valid', models.BooleanField(default=False, help_text='Whether the location is within school premises')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_created', to=settings.AUTH_USER_MODEL)),
                ('recorded_by', models.ForeignKey(help_text='User who recorded this attendance', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='teacher_attendances_recorded', to=settings.AUTH_USER_MODEL)),
                ('schedule', models.ForeignKey(blank=True, help_text='Associated teaching schedule (optional)', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='attendances', to='attendance.teacherschedule')),
                ('substitute_for', models.ForeignKey(blank=True, help_text='Teacher being substituted (if applicable)', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='substituted_by', to='attendance.teacher')),
                ('teacher', models.ForeignKey(help_text='Teacher for this attendance record', on_delete=django.db.models.deletion.CASCADE, related_name='attendances', to='attendance.teacher')),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_updated', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Teacher Attendance',
                'verbose_name_plural': 'Teacher Attendances',
                'ordering': ['-date', 'jp_number', 'teacher__full_name'],
                'indexes': [models.Index(fields=['teacher', 'date', 'jp_number'], name='attendance__teacher_991669_idx'), models.Index(fields=['date'], name='attendance__date_1aa22a_idx'), models.Index(fields=['status'], name='attendance__status_54e06e_idx'), models.Index(fields=['is_substitute'], name='attendance__is_subs_693785_idx'), models.Index(fields=['recorded_by'], name='attendance__recorde_cebba4_idx')],
                'constraints': [models.UniqueConstraint(fields=('teacher', 'date', 'jp_number'), name='unique_teacher_attendance')],
            },
        ),
    ]
