# Generated by Django 6.0.1 on 2026-01-21 07:44

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('attendance', '0013_add_teacher_attendance'),
    ]

    operations = [
        migrations.CreateModel(
            name='TeacherAttendanceSummary',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('year', models.PositiveIntegerField(help_text='Year of the summary')),
                ('month', models.PositiveIntegerField(help_text='Month of the summary (1-12)')),
                ('total_hadir', models.PositiveIntegerField(default=0, help_text='Total number of Hadir (present) JP')),
                ('total_sakit', models.PositiveIntegerField(default=0, help_text='Total number of Sakit (sick) JP')),
                ('total_izin', models.PositiveIntegerField(default=0, help_text='Total number of Izin (permission) JP')),
                ('total_cuti', models.PositiveIntegerField(default=0, help_text='Total number of Cuti (leave) JP')),
                ('total_dinas', models.PositiveIntegerField(default=0, help_text='Total number of Dinas (official duty) JP')),
                ('total_alpa', models.PositiveIntegerField(default=0, help_text='Total number of Alpa (absent without notice) JP')),
                ('total_jp_scheduled', models.PositiveIntegerField(default=0, help_text='Total number of JP scheduled for this period')),
                ('attendance_percentage', models.FloatField(default=0.0, help_text='Attendance percentage (total_hadir / total_jp_scheduled * 100)')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, help_text='Timestamp when summary was created')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='Timestamp when summary was last updated')),
                ('teacher', models.ForeignKey(help_text='Teacher for this summary', on_delete=django.db.models.deletion.CASCADE, related_name='attendance_summaries', to='attendance.teacher')),
            ],
            options={
                'verbose_name': 'Teacher Attendance Summary',
                'verbose_name_plural': 'Teacher Attendance Summaries',
                'ordering': ['-year', '-month', 'teacher__full_name'],
                'indexes': [models.Index(fields=['teacher', 'year', 'month'], name='attendance__teacher_f4c4fa_idx'), models.Index(fields=['year', 'month'], name='attendance__year_46281d_idx')],
                'constraints': [models.UniqueConstraint(fields=('teacher', 'year', 'month'), name='unique_teacher_summary')],
            },
        ),
    ]
