# Generated by Django 6.0.1 on 2026-01-23 11:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('attendance', '0014_add_teacher_attendance_summary'),
    ]

    operations = [
        # Add indexes for Teacher model
        migrations.AddIndex(
            model_name='teacher',
            index=models.Index(fields=['is_active', 'full_name'], name='teacher_active_name_idx'),
        ),
        migrations.AddIndex(
            model_name='teacher',
            index=models.Index(fields=['nip'], name='teacher_nip_idx'),
        ),
        migrations.AddIndex(
            model_name='teacher',
            index=models.Index(fields=['email'], name='teacher_email_idx'),
        ),
        migrations.AddIndex(
            model_name='teacher',
            index=models.Index(fields=['is_homeroom_teacher', 'is_active'], name='teacher_homeroom_idx'),
        ),
        
        # Add indexes for Subject model
        migrations.AddIndex(
            model_name='subject',
            index=models.Index(fields=['is_active', 'category', 'name'], name='subject_active_cat_idx'),
        ),
        migrations.AddIndex(
            model_name='subject',
            index=models.Index(fields=['code'], name='subject_code_idx'),
        ),
        
        # Add indexes for Classroom model
        migrations.AddIndex(
            model_name='classroom',
            index=models.Index(fields=['is_active', 'grade', 'section'], name='classroom_active_idx'),
        ),
        
        # Add indexes for TeacherSchedule model
        migrations.AddIndex(
            model_name='teacherschedule',
            index=models.Index(fields=['teacher', 'day_of_week', 'is_active'], name='schedule_teacher_day_idx'),
        ),
        migrations.AddIndex(
            model_name='teacherschedule',
            index=models.Index(fields=['classroom', 'day_of_week', 'is_active'], name='schedule_class_day_idx'),
        ),
        migrations.AddIndex(
            model_name='teacherschedule',
            index=models.Index(fields=['effective_date', 'end_date'], name='schedule_dates_idx'),
        ),
        
        # Add indexes for TeacherAttendance model
        migrations.AddIndex(
            model_name='teacherattendance',
            index=models.Index(fields=['teacher', 'date', 'jp_number'], name='attendance_teacher_date_jp_idx'),
        ),
        migrations.AddIndex(
            model_name='teacherattendance',
            index=models.Index(fields=['date', 'status'], name='attendance_date_status_idx'),
        ),
        migrations.AddIndex(
            model_name='teacherattendance',
            index=models.Index(fields=['teacher', 'date'], name='attendance_teacher_date_idx'),
        ),
    ]
